// GENERATED by scripts/generate-handset-profiles.mjs - do not edit.
// Source: DevTools emulated-device catalog in the pinned Chromium checkout
// (6a7b3dbec3b2) merged with
// native/seoul/browser/handset/handset_profiles_overlay.json.
// Regenerate: npm run generate:handset   Gate: npm run check:handset-profiles

#ifndef SEOUL_BROWSER_HANDSET_HANDSET_PROFILES_GENERATED_H_
#define SEOUL_BROWSER_HANDSET_HANDSET_PROFILES_GENERATED_H_

#include <string>
#include <vector>

#include "seoul/browser/handset/handset_types.h"

namespace seoul {

// Every device this build can emulate, phones first, featured first.
const std::vector<HandsetProfile>& GeneratedHandsetProfiles();

// Ids of the profiles the picker shows at top level; the rest live under
// "All devices". Computed at generation time - see the generator header.
const std::vector<std::string>& GeneratedFeaturedHandsetProfileIds();

}  // namespace seoul

#endif  // SEOUL_BROWSER_HANDSET_HANDSET_PROFILES_GENERATED_H_
